sudo: required
language: generic 
services:
  - docker
before_install:
  - docker build -t neethumohan1212/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true neethumohan1212/docker-react npm run test